import Head from "next/head";
import Image from "next/image";
import MainLayout from "../components/MainLayout";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen">
        <Hero />
      </div>
    </MainLayout>
  );
}
